### ISSUE TITLE
[Issue] Renaming is not an option

### ISSUE THREAD

**Issue by Kannoma** [JannisX11/snowstorm#10]
**Snowstor variant:** VS Code
**Description:**
If a particle is renamed removing the `.particle` (or just the in between dot) to the name of the particle it will make that particle file unreadable for the plugin even if `.particle` is readded.

eg.
If the particle `rain.particle.json` is renamed in the following order
_rain.particle.json>rain.json>rain.particle.json_
the particle won't be opened with the snowstorm plugin.

This also affects renaming older particles with names not ending for `.particle.json`

**Comment by JannisX11** [comment]
VSCode uses the name of the file at the time it was opened, it does not update the editor type if you rename the file. To open the file in Snowstorm again, you can first close the tab and then open it again. Alternatively, press F1, search for `View: Reopen Editor With...` and select Snowstorm.
