### ISSUE TITLE
Add all the documentation under the help tab onto snowstorm

### ISSUE THREAD

**Issue by Rebelstrike2721** [JannisX11/snowstorm#100]
add the all the documentation under the help tab onto snowstorm so then we dont have to switch tabs and it will all just be in the app

**Comment by JannisX11** [comment]
The last update just added documentation for all fields and features of particles into the documentation panel. Is there any specific information that you are currently missing?

**Comment by Rebelstrike2721** [comment]
I just think it would be nice to have all the documentation just on snowstaorm so then you dont have to be switching between snow storm and browser pages

**Comment by JannisX11** [comment]
Let me repeat that question: For which piece of information  did you have to go to a different website to find it?

**Comment by Rebelstrike2721** [comment]
Format documentation
