### ISSUE TITLE
The particle will not appear because I have set it to SpawnAmount: Mode>Instant, Amount>1 ||| Emitter LifeTime: Mode>Once, Activate>1

### ISSUE THREAD

**Issue by Fluke458** [JannisX11/snowstorm#102]
SpawnAmount: Mode>Instant, Amount>1 ||| Emitter LifeTime: Mode>Once, Activate>1
From the default setting, the Particle does not appear and the timer continues.
![Snowstorm - Google Chrome 18_11_2024 21_38_15](https://github.com/user-attachments/assets/a40c56c2-f904-4445-a84f-d84a0fc84f09)
![Snowstorm - Google Chrome 18_11_2024 21_38_25](https://github.com/user-attachments/assets/83622b80-e93f-472b-b16d-4b358338973f)

**Comment by JannisX11** [comment]
Press the play button at the bottom to play the effect from the beginning and cause a particle to spawn. Or set it to looping.
