### ISSUE TITLE
Start and tick variables get wiped out when editing in the expression bar

### ISSUE THREAD

**Issue by mchorse** [JannisX11/snowstorm#15]
When you try typing anything into the expression bar while any of the tick variables or start variables are being edited, all of the variables from the same category (if you edit a variable from tick variables, all **Tick variables** will be removed, and same with **Start variables**) will be wiped out.

It can be reproduced by creating one or more variables in tick or start variables, input anything in there, then focus to expression bar and input any character. After that all variables in the same category will be removed.

https://user-images.githubusercontent.com/19908073/105628892-94f18300-5e37-11eb-9a89-39a1949bbada.mp4

P.S.: I saw the message in #bb-feedback, so I thought I would report here as well.

**Comment by JannisX11** [comment]
Fixed in 2.2.5
