### ISSUE TITLE
Builtin Particle Variables Don't Allow 'v.' Shorthand

### ISSUE THREAD

**Issue by Kas-tle** [JannisX11/snowstorm#19]
#### Description
When using builtin particle variables, such as `variable.particle_age`, Snowstorm will not properly evaluate the variable unless it is entered using the full name, `variable.particle_age`. The standard shorthand `v.particle_age` is not properly evaluated.

#### Reproduction Steps
- Create a default particle
- Enter a builtin variable in the form `variable.<builtin>` into any field that would produce a visual change, such as direction
- Observe that this variable is properly evaluated
- Change the variable to the form `v.<builtin>`
- Observe the variable is no longer evaluated

#### Affected Platforms
Tested in both the web version and VSCode extension

#### Video Demonstration

https://user-images.githubusercontent.com/26531652/110385035-48db5600-8013-11eb-8a94-85380a0d217f.mp4

**Comment by JannisX11** [comment]
Added in 2.3
