### ISSUE TITLE
Grid does not render lines correctly in Chrome and Edge

### ISSUE THREAD

**Issue by inxomnyaa** [JannisX11/snowstorm#32]
https://youtu.be/wPW7Q-2J1UM

**Comment by JannisX11** [comment]
It renders fine for me. Are you on Windows 10?

**Comment by thebigsmileXD** [comment]
Sure am.
![image](https://user-images.githubusercontent.com/8733998/129456817-ec5a8edd-be23-4315-82d4-f3b495ed3131.png)
```
Microsoft Edge
Version 92.0.902.67 (Official build) (64-bit)
```

FireFox seems to not have that issue, just checked again.
![image](https://user-images.githubusercontent.com/8733998/129456824-938aed90-a0cb-4e35-8563-f41df716093f.png)

Maybe you spot something in the app, not sure.
GPU is a Nv960 with vulkan enabled 
![image](https://user-images.githubusercontent.com/8733998/129456880-4c887e6b-31a5-420d-8fd1-c141e33ea3ca.png)

GPU is a Nv960 with vulkan enabled, not sure if that affects WebGL in any way
![image](https://user-images.githubusercontent.com/8733998/129456906-c3190a4b-e473-4321-92ce-a88cdadea0fb.png)
