### ISSUE TITLE
Array value for `minecraft:particle_initial_speed` is not supported

### ISSUE THREAD

**Issue by stirante** [JannisX11/snowstorm#34]
After importing `knockback_roar.json` vanilla particle, I noticed, that it uses `minecraft:particle_initial_speed` component with an array as a value to define separate speeds for each axis. Snowstorm completely ignored that and instead treated those values as a direction.

Example from `knockback_roar.json`
```json
"minecraft:particle_initial_speed": [ "15 * Math.random(-1.0, 1.0)", "15 * Math.random(-1.0, 1.0)", "15 * Math.random(-1.0, 1.0)" ],
```

**Comment by JannisX11** [comment]
This is intentional since it works exactly the same as a direction.
