### ISSUE TITLE
Performance issues on Android with 'Grid View' enabled.

### ISSUE THREAD

**Issue by r4isen1920** [JannisX11/snowstorm#5]
> Platform: Android
> Browser: Chrome for Android (Version 84.0.4147.89)

I experience a great frame rate drop when the 'Grid View' is enabled. However, the grid view is pretty useful to be disabled in my use case. I thought that this may be a bug as I've been using it lately on Android.

It only does it on Android, since I have tested the Grid View on a Chrome running on Windows 10 and I have found no issues at all.

Thank you for reading, and hope this to be fixed!

(Also, I would like to suggest a mobile-friendly view and a proper UV mapper for convenience similar to Blockbench.)

**Comment by JannisX11** [comment]
I have reduced the grid size in the latest update, let me know if this resolves your issue!

**Comment by JannisX11** [comment]
Fixed in 2.1. There is a new issue in VSCode that creates a sort of ghost tab (https://github.com/microsoft/vscode/issues/111474), but it's not breaking.
