### ISSUE TITLE
[Issue] expressions using curves and molang can incorrectly return 0

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/snowstorm#59]
I tested the following expressions and some variations, I assume all alternative molang expressions behave the same

`v.curve * molang expression` returns 0

`molang expression * v.curve` works correctly

`molang expression * v.curve * v.curve` returns 0

`molang expression * v.curve * molang expression` returns 0

**Comment by JannisX11** [comment]
Is this still an issue? I cannot reproduce it in the latest version.

**Comment by PaulFinnerty** [comment]
Not sure if the web version (restructured or not) is the latest version, but if so yes:

https://github.com/JannisX11/snowstorm/assets/81629481/d41489ce-b237-4c40-ae96-976395c8081b

**Comment by JannisX11** [comment]
Fixed via https://github.com/JannisX11/MolangJS/commit/c6cc24548140118e0a9755fbeacc19cdc65fee95
