### ISSUE TITLE
[Issue] particles without max_lifetime are given one automatically when opening them

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/snowstorm#60]
The `minecraft:particle_lifetime_expression` component can be left empty to make a particle live indefinitely
https://bedrock.dev/docs/stable/Particles#Particle%20Lifetime%20Expression%20component

But when opening a particle system with no "max_lifetime" in Snowstorm, this component is automatically filled with `max_lifetime": 1` (in the Snowstorm UI, it's "Max Age", under "Lifetime")

---

Putting "0" for the "Max Age" of the particle currently works to leave `minecraft:particle_lifetime_expression` empty, having that instead of 1 would work to fix this issue. Something more explicit could be nice, since a lifetime of 0 is unintuitive for beginners

**Comment by JannisX11** [comment]
Fixed in upcoming 3.0.
