### ISSUE TITLE
How does one open a particles file with this extension?

### ISSUE THREAD

**Issue by daggerbyte** [JannisX11/snowstorm#63]
I can't find any documentation on how this extension works. When I open a particles.json file, it just opens in VScode. When I open the extension from the Extensions panel, it just shows me basic readme information, which has led me here, but I don't see any info how this extension is activated.

**Comment by PaulFinnerty** [comment]
If you have any question about how Snowstorm works, it's best to ask in the Blockbench Discord: https://discord.gg/blockbench, there's a channel dedicated to Snowstorm, but you can also make a post in the help channel that corresponds to your format.

Now for the VS Code extension, it should open the particle in a tab like the browser version of Snowstorm: https://snowstorm.app/

Happy to help more in the Discord!
