### ISSUE TITLE
Enter key incorrectly handled when used within a molang variable name

### ISSUE THREAD

**Issue by BigChungus21220** [JannisX11/snowstorm#71]
Not exactly sure how to describe this accurately, so I will just provide steps to reproduce the bug:

1. Open a text box
2. Type a variable, math function, query, or temp variable
eg:   v.abcdefg
3. Move your cursor back with the arrow keys so that you are between characters in the variable
4. Press Enter
result (from my example after pressing left 4 times before enter):   v.abcdefgdefg

other possible results are: 
inserting the name of an existing variable or molang querey / function
inserting a seemingly random character

This appears to be an autocomplete problem

**Comment by JannisX11** [comment]
If you have a variable called abcdefg in your project (even the current one) and you use autocomplete after abc, then abcdefgdefg is the expected result. Characters after the cursor are ignored when using autocomplete.
