### ISSUE TITLE
How to start using it on VSCode?

### ISSUE THREAD

**Issue by sircurse** [JannisX11/snowstorm#77]
Hi there, 

It might be a silly question, but how can I start using it on VSCode? It is not clear, by just hitting F5 doesnt do anything, the file is named accordingly, so what?

Thank you,
Curse.

**Comment by JannisX11** [comment]
Make sure the extension is installed and the particle file is named `<name>.particle.json`
Then it should work.

**Comment by Rebelstrike2721** [comment]
> Make sure the extension is installed and the particle file is named `<name>.particle.json` Then it should work.

Why does it have to be .particle.json?

**Comment by JannisX11** [comment]
To let the extension know that it's a particle file that should be opened with Snowstorm.
