### ISSUE TITLE
[Issue] VS code can't view the code (lol)

### ISSUE THREAD

**Issue by Kannoma** [JannisX11/snowstorm#9]
Snowstor variant: VS Code
Description:
Clicking on the _View Code_ button, VS code will split the screen opening a new instance of the same particle without showing you the actual code

**Comment by SirLich** [comment]
I also have this issue!

**Comment by SirLich** [comment]
From Jannis: Opening the code viewer was broken by VSCode, you can open it again by selecing F1 and selecting "Reopen Editor With" - "Text Editor"

**Comment by JannisX11** [comment]
Fixed in 2.1.
