### ISSUE TITLE
Be able to acctually paint particles within snowstorm

### ISSUE THREAD

**Issue by Rebelstrike2721** [JannisX11/snowstorm#98]

**Comment by JannisX11** [comment]
You can actually paint particles with Snowstorm. There is a tutorial on the Discord server showing it, it's in the Events in Snowstorm tutorial.

**Comment by Rebelstrike2721** [comment]
> You can actually paint particles with Snowstorm. There is a tutorial on the Discord server showing it, it's in the Events in Snowstorm tutorial.

Ok you may well be able to change the Colour of the particle but you cant paint the pixels of the particle individually which is what I was suggesting to add to the app as this would be great help to not just me but others as well
